#!/bin/bash

if [ $# -ne 1 ]; then
    echo "Usage: $0 <filename.cpp>"
    exit 1
fi

filename="$1"

if [ ! -f "$filename" ]; then
    echo "File '$filename' not found."
    exit 1
fi

clang++ "$filename" -std=c++20 -O2 -Wall -Wextra -Wshadow -Wconversion -Wfloat-equal -pedantic -Wformat=2

if [ $? -eq 0 ]; then
    echo "Compilation successful"
    ./a.out
else
    echo "Compilation failed."
    exit 1
fi
